-- ===================================================
-- ملف: sample_data_inserts.sql
-- وصف: بيانات تجريبية لتجربة النظام
-- ===================================================


-- 1. إدخال دول
INSERT INTO COUNTRIES (COUNTRY_NO, COUNTRY_NAME) VALUES ('EG', 'مصر');
INSERT INTO COUNTRIES (COUNTRY_NO, COUNTRY_NAME) VALUES ('SA', 'المملكة العربية السعودية');
INSERT INTO COUNTRIES (COUNTRY_NO, COUNTRY_NAME) VALUES ('JO', 'الأردن');
COMMIT;


-- 2. محافظات (مصر)
INSERT INTO GOVERNORATES (GOV_NO, GOV_NAME, COUNTRY_NO) VALUES (1, 'القاهرة', 'EG');
INSERT INTO GOVERNORATES (GOV_NO, GOV_NAME, COUNTRY_NO) VALUES (2, 'الإسكندرية', 'EG');
COMMIT;


-- 3. أقسام
INSERT INTO PROVINCES (PROVINCE_NO, PROVINCE_NAME, GOV_NO) VALUES (101, 'وسط القاهرة', 1);
INSERT INTO PROVINCES (PROVINCE_NO, PROVINCE_NAME, GOV_NO) VALUES (102, 'حلوان', 1);
COMMIT;


-- 4. مدن
INSERT INTO CITIES (CITY_NO, CITY_NAME, PROVINCE_NO) VALUES (1001, 'ميدان التحرير', 101);
INSERT INTO CITIES (CITY_NO, CITY_NAME, PROVINCE_NO) VALUES (1002, 'مدينتي', 102);
COMMIT;


-- 5. فروع
INSERT INTO BRANCHES_TBL (BRANCH_ID, BRANCH_NAME) VALUES (1, 'الفرع الرئيسي - القاهرة');
INSERT INTO BRANCHES_TBL (BRANCH_ID, BRANCH_NAME) VALUES (2, 'فرع الإسكندرية');
COMMIT;


-- 6. إدارات
INSERT INTO dept (DEPTNO, DEPT_NAME, BRANCH_ID, IS_ACTIVE) 
VALUES (100, 'الموارد البشرية', 1, 'Y');
INSERT INTO dept (DEPTNO, DEPT_NAME, BRANCH_ID, IS_ACTIVE) 
VALUES (200, 'المحاسبة', 1, 'Y');
COMMIT;


-- 7. وظائف
INSERT INTO JOBS (JOB_NO, JOB_NAME, JOB_TYPE) VALUES (1001, 'مدير عام', 1);
INSERT INTO JOBS (JOB_NO, JOB_NAME, JOB_TYPE) VALUES (1002, 'محاسب', 2);
COMMIT;


-- 8. مستخدمين
INSERT INTO users (USER_ID, USER_NAME, USER_PASS, USER_STATUS, SDATE) 
VALUES (SEQ_USER_ID.NEXTVAL, 'admin', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'A', SYSDATE);

INSERT INTO users (USER_ID, USER_NAME, USER_PASS, USER_STATUS, SDATE) 
VALUES (SEQ_USER_ID.NEXTVAL, 'ahmed', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'A', SYSDATE);
COMMIT;


-- 9. موظفين
INSERT INTO emp_data (EMPNO, DEPTNO, BIRTH_DATE, HIRE_DATE, HIRE_TYPE, SEX_TYPE) 
VALUES (10001, 100, DATE '1985-03-15', DATE '2010-06-01', 'I', 'M');

INSERT INTO FIXED_DATA (EMP_NO, EMP_NAME, NATIONAL_NO, HIRE_DATE, SEX_NO) 
VALUES (10001, 'أحمد محمد', '29003151201234', DATE '2010-06-01', 'M');

INSERT INTO SOCIALANDPERSONAL_DATA (EMP_NO, BRITH_DATE, BRITH_PLACE, ADDRESS, TELEPHONE) 
VALUES (10001, DATE '1985-03-15', 'القاهرة', 'شارع التحرير', '01001234567');
COMMIT;


-- 10. أنواع الإجازات
INSERT INTO VACATIONS_TYPE (VAC_NO, VAC_NAME, BLANCE, ADD_OR_REDUCED) 
VALUES (1, 'إجازة سنوية', 21, 'A');
INSERT INTO VACATIONS_TYPE (VAC_NO, VAC_NAME, BLANCE, ADD_OR_REDUCED) 
VALUES (2, 'إجازة مرضية', 30, 'A');
COMMIT;


-- 11. إدخال إجازة
INSERT INTO VAC_INSRT (USER_ID, SERIAL_NO, EMP_NO, VAC_TYPE_NO, SDATE, EDATE, IS_OK, LIST_DATE) 
VALUES (100, 1, 10001, 1, DATE '2025-07-01', DATE '2025-07-21', 'Y', SYSDATE);
COMMIT;


-- 12. عملات
INSERT INTO CURRENCIES (CUR_NUM, CUR_NAM, CUR_COUN) VALUES (818, 'الجنيه المصري', 'EGP');
INSERT INTO CURRENCIES (CUR_NUM, CUR_NAM, CUR_COUN) VALUES (682, 'الريال السعودي', 'SAR');
COMMIT;


-- 13. مستفيدين
INSERT INTO BEN_TBL (BEN_NUM, BEN_NAM, BEN_TYPE_NO) VALUES (SEQ_BEN_NUM.NEXTVAL, 'شركة الاتصالات', 'C');
COMMIT;


-- 14. مستندات
INSERT INTO DOCS_TBL (DOC_NUM, DOC_INFO, DOC_TYPE, INS_DAT, USR, DOC_YEAR) 
VALUES (SEQ_DOC_NUM.NEXTVAL, 'طلب ترقية', 1, SYSDATE, 100, '2025');
COMMIT;


-- 15. أمر صرف
INSERT INTO AMAR_FRDI (SERIAL_NO, DOC_NUM, BEN_NUM, AMAR_TYPE, ALLOW_TYPE_NUM, THE_AMOUNT, SUB_TXT, INS_USR, INS_DAT) 
VALUES ('A0001', '2025000100', 1, 1, 1, 5000, 'صرف بدل سكن', '100', SYSDATE);
COMMIT;

-- تم
PROMPT البيانات التجريبية أُدخلت بنجاح.
